---
- name: Call the playbook run from bastion node to fialover the EDB cluster to Site 2 as the primary. 
  hosts: all
  gather_facts: false
  tasks: 
    - name: Failover EDB cluster to Site 2 as primary/leader. 
      shell: | 
        tpaexec playbook stagecluster /opt/EDB/TPA/architectures/M1/commands/switchover.yml -e "target=zippier"
      chdir: /home/chammer/edb_clusters