- name: Bring down AAP Site 2. 
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Scale AAP CR replicas according to role. 
      redhat.openshift.k8s:
        state: present
        api_version: automationcontroller.ansible.com/v1beta1
        kind: AutomationController
        name: controller-edb-01
        namespace: aap-24-dr
        merge_type: merge 
        definition:
          spec:
            replicas: 0